server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心到动态创建路由的功能，利用微服务明进行路由
      routes:
        - id: payment_reuth       #路由的ID，没有固定规则但要求唯一，建议配合服务
          #        uri: http://localhost:8001 #匹配后提供服务后的路由地址
          uri: lb://CLOUD-PROVIDER-SERVICE  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径匹配后进行路由
            - After=2020-05-29T21:06:43.384+08:00[Asia/Shanghai]  #在这个时间之后才可以访问
#            - Cookie=username,zzyy

        - id: payment_reuth2       #路由的ID，没有固定规则但要求唯一，建议配合服务
          #        uri: http://localhost:8001 #匹配后提供服务后的路由地址
          uri: lb://CLOUD-PROVIDER-SERVICE  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** #断言，路径匹配后进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka