server:
  port: 7001


eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称

  client:

    #flase表示不像注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，我的职责是维护服务器实例，不想要去检索服务
    fatch-register: false
    service-url:
      #设置与Eureka Server 交互的地址查询服务和注册服务都需要这个地址
      defaultZone: http://eureka7001.com:7001/eureka/ #单机版
#      defaultZone: http://eureka7002.com:7002/eureka/ #集群版

#  server:
#    #禁用eureka Server自我保护机制
#    enable-self-preservation: false
#    # 默认时间为2s
#    a-s-g-update-interval-ms: 2000
