server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
spring:
  application:
    name: cloud-orderFeign-service
#设置feign客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，使用与网络情况正常下，两端连接使用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务端读取可用资源所使用的时间
  ConnectTimeout: 5000
logging:
  level:
    #fegin以什么级别监控哪一个接口
     com.atguigu.springcloud.service.PaymentFeignService: debug
